#ifndef RETURNTYPES_H
#define RETURNTYPES_H

typedef enum{
    SPP_OK,
    SPP_ERROR,
    SPP_NULL_POINTER,
    SPP_NOT_ENOUGH_PACKETS,
    SPP_NULL_PACKET,
    SPP_ERROR_NULL_POINTER,
    SPP_ERROR_NOT_INITIALIZED,
    SPP_ERROR_INVALID_PARAMETER,
    SPP_EXCEDED_LIMIT
}retval_t;


#endif